In [ ]:
import pandas as pd
import plotly.express as px
import streamlit as st

In [ ]:
education = pd.read_csv("data/female_education.csv")

education = education.rename(columns={"name": "country"})

education = education.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="education"
)

education["year"] = pd.to_numeric(education["year"], errors="coerce")
education["education"] = pd.to_numeric(education["education"], errors="coerce")

education = education.dropna(subset=["year", "education"])

# optional: make year integer
education["year"] = education["year"].astype(int)
education

      geo       country  year  education
1     ago        Angola  1970        0.5
2     alb       Albania  1970        3.9
3     are           UAE  1970        1.5
4     arg     Argentina  1970        5.5
5     arm       Armenia  1970        5.9
...   ...           ...   ...        ...
6955  wsm         Samoa  2009       12.0
6956  yem         Yemen  2009        0.7
6957  zaf  South Africa  2009        8.5
6958  zmb        Zambia  2009        5.2
6959  zwe      Zimbabwe  2009        6.7

[6959 rows x 4 columns]

In [ ]:
fertility = pd.read_csv("data/fertility_rate.csv")

fertility = fertility.rename(columns={"name": "country"})

fertility = fertility.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="fertility"
)

fertility["year"] = pd.to_numeric(fertility["year"], errors="coerce")
fertility["fertility"] = pd.to_numeric(fertility["fertility"], errors="coerce")
fertility = fertility.dropna(subset=["year", "fertility"])
fertility["year"] = fertility["year"].astype(int)
fertility

       geo       country  year  fertility
0      afg   Afghanistan  1800       7.00
1      ago        Angola  1800       6.93
2      alb       Albania  1800       4.60
3      and       Andorra  1800       2.11
4      are           UAE  1800       6.94
...    ...           ...   ...        ...
58690  wsm         Samoa  2100       2.06
58691  yem         Yemen  2100       1.91
58692  zaf  South Africa  2100       1.74
58693  zmb        Zambia  2100       2.08
58694  zwe      Zimbabwe  2100       1.98

[58695 rows x 4 columns]

In [ ]:
population = pd.read_csv("data/population.csv")

population = population.rename(columns={"name": "country"})

population = population.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="population"
)

population["year"] = pd.to_numeric(population["year"], errors="coerce")
population["population"] = pd.to_numeric(population["population"], errors="coerce")
population = population.dropna(subset=["year", "population"])
population["year"] = population["year"].astype(int)
population

       geo       country  year   population
0      afg   Afghanistan  1800    3280000.0
1      ago        Angola  1800    1567028.0
2      alb       Albania  1800     400000.0
3      and       Andorra  1800       2654.0
4      are           UAE  1800      40153.0
...    ...           ...   ...          ...
58690  wsm         Samoa  2100     383557.0
58691  yem         Yemen  2100  110035634.0
58692  zaf  South Africa  2100   94314448.0
58693  zmb        Zambia  2100   64473916.0
58694  zwe      Zimbabwe  2100   37166572.0

[58595 rows x 4 columns]

In [ ]:
df = education.merge(
    fertility,
    on= ['geo', 'country', 'year'],
    how= 'inner'
)
df = df.merge(
    population,
    on= ['geo', 'country', 'year'],
    how= 'inner'
)
df = df[(df['year']>=1960) & (df['year']<= 2020)]
print(df.head())

   geo    country  year  education  fertility  population
0  ago     Angola  1970        0.5       7.43   5852788.0
1  alb    Albania  1970        3.9       5.16   2181220.0
2  are        UAE  1970        1.5       6.52    286536.0
3  arg  Argentina  1970        5.5       3.09  23878327.0
4  arm    Armenia  1970        5.9       3.33   2475633.0

In [ ]:
fig1 = px.scatter(
    df,
    x="education",
    y="fertility",
    size="population",
    hover_name="country",
    animation_frame="year",
    title="Education vs Fertility Over Time",
    labels={
        "education": "Female Education (Years)",
        "fertility": "Fertility Rate"
    }
)

fig1.show()

In [ ]:
filtered_df = df[df["year"] == 2007]

fig2 = px.scatter(
    filtered_df,
    x="education",
    y="fertility",
    size="population",
    hover_name="country",
    title=f"Education vs Fertility in {2007}",
    labels={
        "education": "Female Education (Years)",
        "fertility": "Fertility Rate"
    }
)

fig2.show()

In [ ]:
education_trend = df.groupby("year", as_index=False)["education"].mean()

edu = px.line(
    education_trend,
    x="year",
    y="education",
    title="Average Female Education Over Time"
)

edu.show()

In [ ]:
fertility_trend = df.groupby("year", as_index=False)["fertility"].mean()

fert = px.line(
    fertility_trend,
    x="year",
    y="fertility",
    title="Average Fertility Over Time"
)

fert.show()

In [ ]:
selected_year = 2007
filtered_df = df[df["year"] == selected_year]

top_education = filtered_df.nlargest(10, "education")

top_edu = px.bar(
    top_education,
    x="education",
    y="country",
    orientation = 'h',
    color_discrete_sequence=["skyblue"],
    title=f"Top 10 Countries by Female Education in {selected_year}"
)
top_edu.update_layout(height=600)
top_edu.update_yaxes(tickmode='linear')
top_edu.update_yaxes(categoryorder = 'total ascending')
top_edu.show()

In [ ]:
selected_year = 2007
filtered_df = df[df["year"] == selected_year]

top_education = filtered_df.nlargest(10, "education")

top_edu = px.bar(
    top_education,
    x="education",
    y="country",
    orientation = 'h',
    color_discrete_sequence=["skyblue"],
    title=f"Top 10 Countries by Female Education in {selected_year}"
)
top_edu.update_layout(height=600)
top_edu.update_yaxes(categoryorder = 'total ascending')
top_edu.show()

In [ ]:
top_fertility = filtered_df.nlargest(10, "fertility")

top_fert = px.bar(
    top_fertility,
    x="fertility",
    y="country",
    orientation = 'h',
    color_discrete_sequence=["skyblue"],
    title=f"Top 10 Countries by Fertility in {selected_year}"
)
top_fert.update_layout(height=600)
top_fert.update_yaxes(categoryorder = 'total ascending')
top_fert.show()

In [ ]:
selected_year = 2007
filtered_df = df[df["year"] == selected_year]

avg_education = filtered_df["education"].mean()
avg_fertility = filtered_df["fertility"].mean()
total_population = filtered_df["population"].sum()

print("Average education:", round(avg_education, 2))
print("Average fertility:", round(avg_fertility, 2))
print("Total population:", round(total_population, 0))

Average education: 7.08
Average fertility: 3.12
Total population: 6675127733.0

In [ ]:
countries_to_compare = ["Nigeria", "Germany"]

compare_df = df[df["country"].isin(countries_to_compare)]

compare_edu = px.line(
    compare_df,
    x="year",
    y="education",
    color="country",
    title="Education Comparison Over Time"
)

compare_edu.show()

In [ ]:
compare_fert = px.line(
    compare_df,
    x="year",
    y="fertility",
    color="country",
    title="Fertility Comparison Over Time"
)

compare_fert.show()

In [ ]:
df.to_csv("education_fertility.csv", index=False)
df= pd.read_csv('education_fertility.csv')
df

      geo       country  year  education  fertility  population
0     ago        Angola  1970        0.5       7.43   5852788.0
1     alb       Albania  1970        3.9       5.16   2181220.0
2     are           UAE  1970        1.5       6.52    286536.0
3     arg     Argentina  1970        5.5       3.09  23878327.0
4     arm       Armenia  1970        5.9       3.33   2475633.0
...   ...           ...   ...        ...        ...         ...
6954  wsm         Samoa  2009       12.0       4.47    191513.0
6955  yem         Yemen  2009        0.7       5.00  25927724.0
6956  zaf  South Africa  2009        8.5       2.50  51728516.0
6957  zmb        Zambia  2009        5.2       5.45  13490389.0
6958  zwe      Zimbabwe  2009        6.7       3.95  13142790.0

[6959 rows x 6 columns]

No kernel connected